PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX o: <http://example.org/ontology/>
SELECT ?s ?g {
  ?data
    rdfs:label ?l .

  ?pjs
    o:predicateJoinSummaryOf ?data .

  ?dist
    a o:SparqlEndpointDistribution ;
    o:of ?pjs ;
    o:service ?s ;
    o:graph [
      rdf:_1 ?g
    ] .
}
